exclude two collection codes from export
pulibrary/aspace_helpers pull request #557
Opened 2024-05-29 19:59 UTC by regineheberlein

closes #556 and #553

2024-05-29 20:10 UTC, maxkadel requested changes
You have a lot of methods commented out - could you just confirm that that's on purpose? I wasn't sure if it was for testing and not intended to be kept long-term.

2024-05-29 20:10 UTC, rladdusaw approved these changes

2024-05-29 22:28 UTC, regineheberlein commented
> You have a lot of methods commented out - could you just confirm that that's on purpose? I wasn't sure if it was for testing and not intended to be kept long-term.

Thanks for catching that @maxkadel !

2024-05-30 14:17 UTC, maxkadel approved these changes
Thanks @regineheberlein !

2024-05-30 14:18 UTC, merged