preliminary success sorting the namespace/regex issue; to be reviewed
pulibrary/aspace_helpers pull request #588
Opened 2024-09-03 21:56 UTC by regineheberlein

2024-10-15 18:57 UTC, maxkadel commented on spec/reports/aspace2alma/get_MARCxml_spec.rb
> +require 'nokogiri'
Do we still need to add nokogiri here?

2024-10-23 19:57 UTC, regineheberlein commented on spec/reports/aspace2alma/get_MARCxml_spec.rb
> +require 'nokogiri'
Yes, line 70!

2024-10-23 20:05 UTC, regineheberlein commented on spec/reports/aspace2alma/get_MARCxml_spec.rb
> +require 'nokogiri'
no, we don't!

2024-10-24 14:41 UTC, maxkadel approved these changes
Thanks @regineheberlein !

2024-10-24 14:46 UTC, maxkadel requested changes
Wait! I think we might still need nokogiri in get_MARCxml.rb, I think we just don't need it in the spec?

2024-10-29 18:17 UTC, maxkadel approved these changes
Thanks!

2024-10-29 18:17 UTC, merged